### PR TITLE
Removes bad usage of count and improves string parsing

### PR DESCRIPTION
**Pull request by Shardj**

### CODE REVIEW

**Comment by unhawkable** [comment]
Thank you!

**Comment by unhawkable** [comment]
Yes. If only I could do it in one place for all repos in the organisation... otherwise I'd need to edit settings of 90 repos one by one by hand

**Comment by Shardj** [comment]
@unhawkable thank you, that's great. By the way, what do you use to install these modules? The include paths seem to not work through regular composer installation as the structure is different to a full zf1 install. I won't raise an issue for this since this is really an issue with me not the codebase.

`Fatal error: require_once(): Failed opening required 'Zend/Loader/Autoloader.php' (include_path='.:/usr/local/lib/php') in /srv/www/vendor/zf1s/zend-application/library/Zend/Application.php on line 81`

**Comment by Shardj** [comment]
image

Picture of current structure, as is installed by composer.json by requiring each module needed individually

**Comment by unhawkable** [comment]
That seems like a leftover in zf1s\zend\application - that require_once should be commented out there, similar to all other require_once-s... no idea why I did not catch that one

**Comment by Shardj** [comment]
I'll do a search for all includes and requires in modules other than loader and raise an issue for them then @unhawkable. I'd make a pr but I don't know what I'm doing with them, is it really as simple as commenting them out?

**Comment by unhawkable** [comment]
there are only two leftovers in Zend_Application. I scanned all other packages and everything is commented out. So the one in constructor should be just commented out and the code in setBootstrap method: ```
if (!class_exists($class, false)) {
            require_once $path;
            if (!class_exists($class, false)) {
                throw new Zend_Application_Exception(
                    'Bootstrap class not found'
                );
            }
        }```
should be modified to:
```        if (!class_exists($class)) {
                throw new Zend_Application_Exception(
                    'Bootstrap class not found'
                );
        }```
The rule is that composer autoloader should be used only.

**Pull request merged**
